language: python
python: '3.9'
node_js: 10.16.3
before_install:
- npm install dredd@14.0.0 --global
- pipenv install --dev
script:
- dredd oas.yaml http://127.0.0.1:8000 --hookfiles=./hooks.py --language=python --server
  "uvicorn todo.server:server"
deploy:
  provider: heroku
  api_key:
    secure: TsyX6jE6wBuYb9WcOUAxHrFOHBvfgSJl7JD9tiDPPCBW587UYmaHBEIq01+c2VydttXGJRSaBmy33ELzCuCv2zv/Cp/+x/TScu2/ZmwuzBVG7mP2uc2qywFQ453NttxSAeR2khsKDs9FlbmY8jajZJxwZ8UcfayipH+1DCp/XeNkYpjpe5NCnbTZQPd7Tqe3rZewr8Dmhq07J5aKwXZjVjx7ugVHcTWNnDreRk0wUQ5LYR1g2XSPXsw15meNyugscGl+90QcDFUNyDZ7TH20Dg7+MrsqH+GBCAGfa2vZXw4PZOsh/Jn2vCqmEcUEZC1nGwMG5lrQlXBgG0rNLYe2jvEFJgbc/buN/Bm8kr9qCPerCN0Ojo1SSrm9YlV8rzJvfFy80ZOPXAcq/bqyEZz+ugPvOa6OU4e79YKFDvRtB3oKGNm6slkROvK/b06eZdo6JgWx+u3Unt4XDF0pv7Xy0V97mVSkhQY2QOhZDe94HS4HcnTKW05T1QMEyKZ8Va0BOhGqgnulrzqeMiJAfF42dVYMnMp79X6HaaXKM7fRp9b5zUtHjTwlEZANOMg0hncpjUQXJMncu65feDxa+P1fpcVyqSGnHk+XGYPJzwcfxxHm62xe3MqCvKTntVElDSgIG8QgEKj39djWrioHKJ1OkMn1ESFsH0DC0lmzpaaCrXI=
  app:
    master: manning-twitch
