language: python
python: '3.9'
node_js: 10.16.3
before_install:
- npm install dredd@14.0.0 --global
- pipenv install --dev
script:
- dredd oas.yaml http://127.0.0.1:8000 --hookfiles=./hooks.py --language=python --server
  "uvicorn todo.server:server"
deploy:
  provider: heroku
  api_key:
    secure: vVm2GR4ThU3cFaJ/qzX6FYKeKPNscMwuL66K+vzEkSPi5dhhIrNZ4wTrDjQDvAJfZEx1VLbLkqBAgE4SRoUEn47yS/wgRfbVr4UBvmhyJjw3xooLjY+OGmWNiS3E4ULruywK7lmrW9mOvRqnYquAIsAdZCruOyEY2f5Sj8MQBGw9m0BRXLFRmtmWeCb6iGSgTxsGgQw6x4fo3IBQmuNr9TcWZSOqkhWyp0T0YTOkQYMiwrbxguai2xrz3uwh8XIYQ/YO1AMFz6kmrFRdb7rGjh+z7RIicCSz7gFTipSd39HwSEk1fFW8iHv8g5cQvbroge1mSzYbAalAPxYRgxL+XcTjKWVANRpYQHJBf0hrFmAHk7pKczoB2HqkrQafBGW06Er0hTmhEqf0dc/n7CigjrUEWnyn+YzmriDLCwm3KTKScnejnaHhq+KmA3F87Gp5nYRJh7uYr8RaNXRuyeX70m1jSWfqd04UQyiu/a3GzGX4lrEGauPWHUGjaBHLcySh30rMP/xdQ5gaoz9NRcAcorqnH22upyBmEOAmj6EW+F8sA72B+HlKcrcJXxtB34TtVOlTB5FBGIpx6Yfv/5Z8v8V1/OZ+ixYv32dD6PcVg/aSxu7PhAsuVo+XgEEAYYjIL60BXGN6XOwCMtPtK5M57oJio4q9QgGv/WpCwmocHIg=
  app:
    master: manning-twitch
