language: python
python: '3.9'
node_js: 10.16.3
before_install:
- npm install dredd@14.0.0 --global
- pipenv install --dev
script:
- dredd oas.yaml http://127.0.0.1:8000 --hookfiles=./hooks.py --language=python --server
  "uvicorn todo.server:server"
deploy:
  provider: heroku
  api_key:
    secure: 19akOwaqYk8ufA8+e+gBubi05cmPWKqQA74VRNymHdY8zTXIxiRAIV89wbYDLFNsZwlAQ99N5+Nn7o6ELOlJktl/NR7sw7MOHh2E+vbIfcL9mrVNGbK4ofv6K3WI9umNIlQRDvcqHMemHb1SVimXzQ+DBnSjN1TNqOaqCkvftBbCiHu2vntIgS1MzUH27BbKTYjiuA00vqWigO4eBcBhgr283hAkQSlb0nckTlmKxcdROVIBd7L/O1YSeu0JVVr0S+5oQCAtzyxV6PZChk5QtA2mzy+4mWnW/bYSjTLy/2db/SqvgxqZjVvx3AFwWm5qhkNJyNMwuIYY1s2jyBeXIHVF7qrlId4qeAZg8WzmLYKc3HYFPndhHFimgob5sRR1a9ddh4uAV3v5eyfqm7Y6xuz4UABYP1uPxDPsjQgAgTv6GmGmpVl9kk/R1tcmhJWULli8BR75rGrdWRqD88GVz5LD7tnRndxH7nhIoqOidKK2cXMlya/cVlAQjNPyGmvGnNer1Pm+mv9LfTDlN72IZqtcdXPapvFexuigz+ZVUhpVe/HBeR1hoY/HmQu0sVgmG6QuMNF+ZE24/UVS2FDp37cUp0u2PZZ42rYy6LCkiOJNr5pLh1qyGxOkzlQ6EgwlI4TdbyMc9Ql18WPJ1SjjniQkJ5uQAilI3noGelwvtVA=
  app:
    master: manning-twitch
